services:
  mock-collector:
    image: ghcr.io/apache/skywalking-agent-test-tool/mock-collector:latest
    ports:
      - "12801:12800"
    healthcheck:
      test: ["CMD", "bash", "-c", "cat < /dev/null > /dev/tcp/127.0.0.1/12800"]
      interval: 5s
      timeout: 10s
      retries: 10
    networks: [e2e]

networks:
  e2e:
